moved black run due to permissions issue

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -35,7 +35,7 @@ jobs:
       - name: Install linters
         run: |
           python -m pip install --upgrade pip
-          pip install bandit[toml] pycodestyle pylint
+          pip install bandit[toml] pycodestyle pylint black
 
       - name: Run pycodestyle
         run: |
@@ -50,3 +50,8 @@ jobs:
         if: success() || failure() # still run bandit if above checks fail
         run: |
           bandit -c pyproject.toml -r .
+
+      - name: Run black
+        if: success() || failure() # still run black if above checks fails
+        run: |
+          black --check --verbose --line-length 120 .
